### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by zeromtmu** [hyperopt/hyperopt-sklearn#102]
I try to install from 

`git clone git@github.com:hyperopt/hyperopt-sklearn.git`

but it said

`Cloning into 'hyperopt-sklearn'...
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.`

**Comment by meenaparam** [comment]
You could try the HTTPS version: `git clone https://github.com/hyperopt/hyperopt-sklearn.git`

**Comment by Seanny123** [comment]
Got the same error and resolved it in the same way. I think this issue can be closed.
