### ISSUE TITLE
How to disable preprocessing in HyperoptEstimator?

### ISSUE THREAD

**Issue by taoxinyi** [hyperopt/hyperopt-sklearn#129]
In `estimator.py` , when `preprocessing` is `None` in `HyperoptEstimator`, it will use a preprocessing anyway.

```python
if preprocessing is None:
    preprocessing = components.any_preprocessing('preprocessing')
```
Is it possible to not use preprocessing at all?

**Comment by bjkomer** [comment]
yes, you can pass an empty list `[]` to use no preprocessing
