### ISSUE TITLE
How to do multioutput Regression and Regressor Chain ?

### ISSUE THREAD

**Issue by Abhranta** [hyperopt/hyperopt-sklearn#178]
I have a dataset where I have to predict 3 days in advance. So, I am thinking of using sklearn's regressor chain to solve this problem. Does hpsklearn support regressor chain and multioutput regressioo. If yes, then how can i implement it ??

**Comment by stb-f5c** [comment]
similar question, is it possible to use hyperOpt to tune a multioutput regression model?

**Comment by mandjevant** [comment]
Currently, usage of the `MultiOutputRegressor` class in hyperopt-sklearn is not supported.
For tips on using the hyperopt base algorithm for your issue, I would suggest writing an issue at https://github.com/hyperopt/hyperopt
