### ISSUE TITLE
install requirment

### ISSUE THREAD

**Issue by john-zeng112** [hyperopt/hyperopt-sklearn#180]
for the install requirments. Which version should be used? 
 install_requires = [
        'hyperopt',
        'nose',
        'numpy',
        'scikit-learn',
        'scipy',
    ],

**Comment by bostjangec** [comment]
For me:

hyperopt        0.2.5
nose            1.3.7
numpy           1.22.0
scikit-learn    1.0.2
scipy           1.7.3

**Comment by mandjevant** [comment]
Thank you for raising an issue.
The supported package versions for use and for development are now displayed in [requirements.txt](https://github.com/hyperopt/hyperopt-sklearn/blob/master/requirements.txt) and [requirements_dev.txt](https://github.com/hyperopt/hyperopt-sklearn/blob/master/requirements_dev.txt) respectively.
