### ISSUE TITLE
distribute via gh vs pypi?

### ISSUE THREAD

**Issue by darenr** [hyperopt/hyperopt-sklearn#191]
This isn't really an issue, but I wonder why distribute this via GH rather than the usual conda/pypi? Is there some advantage to this approach? Just curious about the thinking behind this.

**Comment by mandjevant** [comment]
I'm not sure what the legacy reason for this is since I was not around when the project started. 
All I can say is that publishing the current version of hyperopt-sklearn on Pypi is on the roadmap 😄
