### ISSUE TITLE
Catboost classification and regression 

### ISSUE THREAD

**Issue by prativapokhrel** [hyperopt/hyperopt-sklearn#192]
Is there no catboost included in classification and regression options? 
![image](https://user-images.githubusercontent.com/20887144/203167249-fd487f38-786b-4cba-b6d2-3dba9b01621f.png)

**Comment by mandjevant** [comment]
There is not.
Catboost classifier is not in scikitlearn either.

**Comment by prativapokhrel** [comment]
Thank you for replying.
