### ISSUE TITLE
InvalidParameterError, possible package version issue?

### ISSUE THREAD

**Issue by JuliaWasala** [hyperopt/hyperopt-sklearn#193]
When running the HyperoptEstimator, I get the following 
`error:sklearn.utils._param_validation.InvalidParameterError: The 'base_estimator' parameter of AdaBoostClassifier must be an object implementing 'fit' and 'predict' or a str among {'deprecated'}. Got None instead.`

I have a feeling this might be a package version issue. Do you know how I could solve it?
Versions: 
- Python: 3.9.15
- hpsklearn: 1.0.3
- numpy: 1.23.5
- scikit-learn 1.2.0
- scipy 1.9.3

**Comment by JuliaWasala** [comment]
update: downgrading scikit-learn to 1.1.0 works -- an AdaBoostClassifier parameter that is set is deprecated in version 1.2.0. would be good to update the requirements.

**Comment by mandjevant** [comment]
Thank you for letting us know! 
Feel free to supply a pull request with the requirements changes.
I will update hyperopt-sklearn to work with scikit-learn 1.2.0 soon.
