### ISSUE TITLE
Add LICENSE to PyPi sdist

### ISSUE THREAD

**Issue by YannickEttwein** [hyperopt/hyperopt-sklearn#202]
Hello,

I recently noticed that the sdist for hyperopt-sklearn version 0.1.0 on PyPi does not include the LICENSE.txt file. Including the license file in the sdist is important for compliance and clarity regarding the terms under which the software is distributed.

Could you please include the LICENSE.txt file in the PyPi sdist for future releases? This small addition would greatly assist users in understanding the licensing terms and ensure proper usage within their projects.

Thank you for your continued work on hyperopt-sklearn.

Cheers,
Yannick

**Comment by mandjevant** [comment]
The PyPi page is highly outdated. Additionally, I don't have access to it.
I suggest installation from github repository directly, using pip: 
`pip install git+https://github.com/hyperopt/hyperopt-sklearn`

On this repository, the license is available.
