### ISSUE TITLE
[RELEASE] PyPI Release Request

### ISSUE THREAD

**Issue by itellaetxe** [hyperopt/hyperopt-sklearn#209]
## Context

Dear `hyperopt-sklearn` developer team,

We are under heavy development of a Python [package](https://github.com/compneurobilbao/ageml) that is dependent on `hyperopt-sklearn`.

As part of our 0.2.0 release, we added your package as a dependency to our project. However, we are having an issue with publishing our package to PyPI, as we specified `hyperopt-sklearn` as a direct dependency taken from the current `main` branch of this repository (directly linked to GitHub commit). PyPI does not support direct dependency specification when publishing to it, so I would need to specify `hyperopt-sklearn` as a dependency from PyPI.

### Request
To solve our publishing blockage, it would be great if you could publish the last `hyperopt-sklearn` version (commit [4bc2864](https://github.com/hyperopt/hyperopt-sklearn/tree/4bc286479677a0bfd2178dac4546ea268b3f3b77)) to PyPI. This way we could specify your package as a PyPI dependency, and not a direct one.

### Workaround
If publishing your package to PyPI is not in your close-term plans, we are planning to create a fork of this repository and publish the new version ourselves, tagging it as `hyperopt-sklearn-unofficial`, and clearly stating the circumstances related to that release. This would happen next week.
Another alternative would be to declare a static fork of the package as a submodule of our project, but this is not optimum for keeping our package clean of other code.

Thank you for considering our request :)!

**Comment by mandjevant** [comment]
Thanks for reaching out! 

I/we do not have access to the pypi hyperoptsklearn page and thus cannot update it. We have previously discussed publishing the package under an official pypi with a different name. But since this has no urgency, we haven't gotten around to it.

I can look into it again but Im certain that this will not be done within the week due to my schedule. 

Normally, we recommend putting a link to our install guide in the readme. That is what I'd recommend in this situation as well.

**Comment by FanwangM** [comment]
Putting `hyperopt-sklearn = { git = "https://github.com/hyperopt/hyperopt-sklearn.git", branch = "master"}` into `pyproject.toml` can be a solution.  This trick was used in https://github.com/theochem/procrustes/issues/197 as a temporary solution. Another way is to add `dependencies = [
  "hyperopt-sklearn@git+https://github.com/hyperopt/hyperopt-sklearn#egg=master",
]` into `pyproject.toml`. Hope this can work. @itellaetxe

**Comment by mandjevant** [comment]
@itellaetxe 
We now have an official pypi release: https://pypi.org/project/hyperopt-sklearn/
