### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by useanalias** [hyperopt/hyperopt-sklearn#37]
Hello!

On line 72 of `setup.py`, there is a line that reads

`subdirectories = os.walk(package_to_path(package)).next()[1]`

but to be compatible with Python 3 as well, this should read

` subdirectories = next(os.walk(package_to_path(package)))[1]`

I cloned the repository and tested this out myself, and it installed without a hitch in Python 3.5. Would there be a chance this change could be implemented in the repository?

**Comment by nouiz** [comment]
Just a comment, I don't have any access to this repository. If you make a
PR, there is more chance it get merged. I saw other PR get merged with some
delays.

**Comment by useanalias** [comment]
Thank you @nouiz!

**Comment by useanalias** [comment]
I've actually found there are a couple more issues with Python 3 compatibility as well (imports, etc.) - I'll deal with those and see if the tests check out. Thank you!

**Comment by useanalias** [comment]
For anyone curious, I've opened a pull request with my edits included.
