### ISSUE TITLE
How to pass "probability=True" to a support vector machine classifier?

### ISSUE THREAD

**Issue by matalab** [hyperopt/hyperopt-sklearn#49]
I need to pass **probability=True** to **SVC** algorithm, because it is used later for ensemble soft voting classifier (VotingClassifier) and therefore probability calculated is required. 
I tried with the following, but get the error: "Error: _svm_hp_space() got an unexpected keyword argument 'probability'"

```
svc1 = HyperoptEstimator(preprocessing = [],
	classifier=svc('my_svc', probability=True),
	algo=hyperopt.tpe.suggest,
	trial_timeout=120.0
	max_evals=100,
	verbose=2)
```

How to pass this probability=True parameter value to the SVC classifier utilizing hpsklearn?

**Comment by bjkomer** [comment]
Looks like that parameter was missed. It may not have existed in scikit-learn 0.13 which was the latest version when hpsklearn was created. I'll add it in, should be a quick fix. The syntax you used will be correct.

**Comment by matalab** [comment]
Many thanks, bjkomer!
