### ISSUE TITLE
Hyperopt-sklearn For Regression

### ISSUE THREAD

**Issue by fundamentalist** [hyperopt/hyperopt-sklearn#56]
After going through the code, I tried to implement the optimization for multivariate regression as follows.
from hyperopt import hp
from hpsklearn import regressor
estimreg = hyperopt_estimator(regressor =any_regressor('reg')
estimreg.fit(X_train,y_train)

It gives me a error. I am not able to run any regression algorithms. Is this a limitation ?

**Comment by bjkomer** [comment]
What is the error that you are getting? In the code you wrote above you have to import `any_regressor` rather than `regressor`

**Comment by fundamentalist** [comment]
I did import any_regressor, but the issue was something different related to the setup on my machine. I reinstalled it and was working fine. Thanks
