### ISSUE TITLE
cannot import name 'hyperopt_estimator'

### ISSUE THREAD

**Issue by Decrayer** [hyperopt/hyperopt-sklearn#57]
I tried to run the example code:

```
from hpsklearn import svc, hyperopt_estimator
from sklearn import svm

if use_hpsklearn:
    estim = hyperopt_estimator( classifier=svc('mySVC') )
else:
    estim = svm.SVC( )

estim.fit( X_train, y_train )

print( estim.score( X_test, y_test ) )
```

But I get the following error message:

> 
>   File "E:/Dokumente/somefolder/untitled0.py", line 1, in <module>
>     from hpsklearn import svc, hyperopt_estimator
> 
> ImportError: cannot import name 'hyperopt_estimator'

Note: I can import svc, it's just the hyperopt_estimator that causes errors.

**Comment by bjkomer** [comment]
Try importing and using `HyperoptEstimator` instead of `hyperopt_estimator`. At some point this got renamed to better reflect that it is a class rather than a function, but it looks like the old one is still used in some of the examples. That should get fixed.

**Comment by Decrayer** [comment]
Ok, thank you, that worked for me.
