### ISSUE TITLE
Number of initial evaluations

### ISSUE THREAD

**Issue by Wagner-Alvarenga** [hyperopt/hyperopt-sklearn#80]
Hi,
I am doing some tests with hyperopt-sklearn, and I was wondering how the initial number of random trials may be set. 
Thank you in advance

**Comment by bjkomer** [comment]
I'm assuming you mean the initial set of random trials for the `tpe` algorithm. This is a parameter of its `suggest` method called `n_startup_jobs` which defaults to 20. You can set this when you pass it to either `hyperopt` or `hyperopt-sklearn` by using [partial functions](https://www.learnpython.org/en/Partial_functions) (I'll show an example below). You can see the other parameters you can set as well as their defaults in the [source code](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/tpe.py#L823).

The example below shows how you would run the `tpe` algorithm for 50 trials with the first 10 being random initial trials:

```
from hpsklearn import HyperoptEstimator, any_classifier, tpe
from functools import partial

estim = HyperoptEstimator(classifier=any_classifier('my_clf'),
                          preprocessing=[],
                          algo=partial(tpe.suggest, n_startup_jobs=10),
                          max_evals=50)
```
