### ISSUE TITLE
Why requires NumPy==1.11.0?

### ISSUE THREAD

**Issue by aht** [hyperopt/hyperopt-sklearn#86]
Is there a specific problem with other versions? For example, our infrastructure uses numpy-1.13.3 and installing hyperopt-sklearn basically downgrades numpy.

It seems both sklearn and hyperopt only specifies generic numpy dependency.

**Comment by jaberg** [comment]
i suspect a packaging error, @brent?

**Comment by gigglegrig** [comment]
same error with Numpy. It's uninstalling my Numpy1.13 and replace with Numpy 1.10, but failed.

**Comment by bjkomer** [comment]
There was an [issue](https://github.com/hyperopt/hyperopt-sklearn/issues/60) that came up with Numpy 1.12, so a workaround was to fix it to 1.11 where it worked.

This was a while ago so it's possible the newer numpy 1.13 is okay. If not, we'll have to figure out where it is coming from and fix it on our end.

**Comment by gigglegrig** [comment]
Yeah, I realized that too. The problem is Python 3.6 doesn't run with Numpy 1.11.
Hope this can be addressed~ Thanks

**Comment by aht** [comment]
@bjkomer I can verify that auto-sklearn works with numpy-1.13

**Comment by bjkomer** [comment]
Thanks! I've verified it as well, and hyperopt-sklearn works with numpy-1.13. The setup.py has been updated
