### ISSUE TITLE
TypeError when calling estim.fit()

### ISSUE THREAD

**Issue by liyan0628** [hyperopt/hyperopt-sklearn#91]
when I try example:
from hpsklearn import HyperoptEstimator, any_classifier
from sklearn.datasets import load_iris
from hyperopt import tpe
import numpy as np
iris = load_iris()

X = iris.data
y = iris.target

test_size = int(0.2 * len(y))
np.random.seed(13)
indices = np.random.permutation(len(X))
X_train = X[ indices[:-test_size]]
y_train = y[ indices[:-test_size]]
X_test = X[ indices[-test_size:]]
y_test = y[ indices[-test_size:]]

estim = HyperoptEstimator(classifier=any_classifier('my_clf'),
                          algo=tpe.suggest,
                          max_evals=100,
                          trial_timeout=120)

estim.fit(X_train, y_train)

print( estim.score( X_test, y_test ) )

there is something wrong in estim.fit(X_train, y_train)

Results in this error:TypeError: 'generator' object is not subscriptable

**Comment by liyan0628** [comment]
error detail is like this:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-94b0291aea0a> in <module>()
      1 
----> 2 estim.fit(X_train, y_train)
      3 
      4 # Show the results
      5 

/anaconda3/lib/python3.6/site-packages/hpsklearn/estimator.py in fit(self, X, y, EX_list, valid_size, n_folds, cv_shuffle, warm_start, random_state, weights)
    744             increment = min(self.fit_increment,
    745                             adjusted_max_evals - len(self.trials.trials))
--> 746             fit_iter.send(increment)
    747             if filename is not None:
    748                 with open(filename, 'wb') as dump_file:

/anaconda3/lib/python3.6/site-packages/hpsklearn/estimator.py in fit_iter(self, X, y, EX_list, valid_size, n_folds, cv_shuffle, warm_start, random_state, weights, increment)
    655                               #    so we notice them.
    656                               catch_eval_exceptions=False,
--> 657                               return_argmin=False, # -- in case no success so far
    658                              )
    659             else:

/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py in fmin(fn, space, algo, max_evals, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin)
    305             verbose=verbose,
    306             catch_eval_exceptions=catch_eval_exceptions,
--> 307             return_argmin=return_argmin,
    308         )
    309 

/anaconda3/lib/python3.6/site-packages/hyperopt/base.py in fmin(self, fn, space, algo, max_evals, rstate, verbose, pass_expr_memo_ctrl, catch_eval_exceptions, return_argmin)
    633             pass_expr_memo_ctrl=pass_expr_memo_ctrl,
    634             catch_eval_exceptions=catch_eval_exceptions,
--> 635             return_argmin=return_argmin)
    636 
    637 

/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py in fmin(fn, space, algo, max_evals, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin)
    312 
    313     domain = base.Domain(fn, space,
--> 314                          pass_expr_memo_ctrl=pass_expr_memo_ctrl)
    315 
    316     rval = FMinIter(algo, domain, trials, max_evals=max_evals,

/anaconda3/lib/python3.6/site-packages/hyperopt/base.py in __init__(self, fn, expr, workdir, pass_expr_memo_ctrl, name, loss_target)
    784         before = pyll.dfs(self.expr)
    785         # -- raises exception if expr contains cycles
--> 786         pyll.toposort(self.expr)
    787         vh = self.vh = VectorizeHelper(self.expr, self.s_new_ids)
    788         # -- raises exception if v_expr contains cycles

/anaconda3/lib/python3.6/site-packages/hyperopt/pyll/base.py in toposort(expr)
    713         G.add_edges_from([(n_in, node) for n_in in node.inputs()])
    714     order = nx.topological_sort(G)
--> 715     assert order[-1] == expr
    716     return order
    717 

TypeError: 'generator' object is not subscriptable

**Comment by liyan0628** [comment]
Networkx-2.0 is the culprit of the error and downgrading to version 1.11 does the trick.

**Comment by bjkomer** [comment]
This looks like the issue referenced [here](https://github.com/hyperopt/hyperopt/issues/325) with hyperopt and the latest version of networkx. This has been [fixed](https://github.com/hyperopt/hyperopt/pull/319) in the master for hyperopt but it might not be on the pypi yet.

You could try installing the latest version of hyperopt
```
pip install git+https://github.com/hyperopt/hyperopt
```
or downgrading to the older version of networkx
```
pip install networkx==1.11
```

**Comment by bjkomer** [comment]
You just beat me to it! I'll close this issue now.
