### ISSUE TITLE
Feature Request : partial_fit 

### ISSUE THREAD

**Issue by nicaogr** [hyperopt/hyperopt-sklearn#99]
Do you know if it is easy to implement the partial_fit  for SGDClassifier from scikit-learn in hyperop-sklearn ? 

I would like to train  SGDClassifier online per batch.

**Comment by bjkomer** [comment]
There is a `use_partial_fit` argument to the [HyperoptEstimator](https://github.com/hyperopt/hyperopt-sklearn/blob/master/hpsklearn/estimator.py#L485). Is that what you are looking for?

**Comment by nicaogr** [comment]
Yes it seems to be what I am looking for.
